---
# tasks file for apache

- include_vars: "{{ ansible_os_family | default('default')}}.yml"

- name: install apache
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "{{ item }}"
    state: "present"
  with_items: "{{ apacke_pkgs }}"

- name: configure apache
  template:
    src: "{{ apache_config | basename }}.j2"
    dest: "{{ apache_config }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
  notify: "apache restart"
    
