---
- hosts: all
  remote_user: vagrant
  become: true
  tasks:
    - assert: 
        that: "ansible_os_family == 'RedHat'"

    - get_installed:

    - debug: var=hostvars[inventory_hostname]['packages_installed']

    - debug: msg='do something when httpd is installed'
      when: "'httpd' in packages_installed"
